name: Gerar Base Parquet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pandas pyarrow google-api-python-client google-auth-httplib2 google-auth-oauthlib pypdf toml

      - name: Executar Consolidador
        run: |
          python gerar_base.py

      - name: Salvar Parquet no Repositorio
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dados_consolidados.parquet
          git commit -m "Auto: Atualizar dados_consolidados.parquet" || exit 0
          git push
